/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.klix;

import app.klix.order.KlixRejectReason;
import app.klix.request.ApproveOrderRequest;
import app.klix.request.GetOrderRequest;
import app.klix.request.RejectOrderRequest;
import app.klix.rest.KlixConnector;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.common.base.Preconditions;
import lombok.ToString;
import org.apache.http.client.HttpClient;
import org.apache.http.impl.client.HttpClients;

@ToString
public final class KlixClient {

    private KlixEnvironment environment = KlixEnvironment.STAGING;

    private String apiKey;
    private byte [] privateKey;
    private String merchantCertificateId;

    private final HttpClient httpClient = defaultHttpClient();

    private final ObjectMapper objectMapper = objectMapper();

    private HttpClient defaultHttpClient() {
        return HttpClients.createDefault();
    }

    public KlixEnvironment getEnvironment() {
        return environment;
    }

    public void setEnvironment(KlixEnvironment environment) {
        this.environment = environment;
    }

    public String getApiKey() {
        return apiKey;
    }

    public void setApiKey(String apiKey) {
        this.apiKey = apiKey;
    }

    public byte [] getPrivateKey() {
        return privateKey;
    }

    public void setPrivateKey(byte [] privateKey) {
        this.privateKey = privateKey;
    }

    public String getMerchantCertificateId() {
        return merchantCertificateId;
    }

    public void setMerchantCertificateId(String merchantCertificateId) {
        this.merchantCertificateId = merchantCertificateId;
    }

    public HttpClient getHttpClient() {
        return httpClient;
    }

    public ObjectMapper getObjectMapper() { return  objectMapper; }

    public void validate() {
        Preconditions.checkNotNull(apiKey);
        Preconditions.checkNotNull(privateKey);
        Preconditions.checkNotNull(merchantCertificateId);
    }

    public GetOrderRequest retrieveOrderDetails(KlixConnector connector, String merchantId, String orderId) {
        GetOrderRequest getOrderRequest = new GetOrderRequest(connector);
        getOrderRequest.withMerchantId(merchantId);
        getOrderRequest.withOrderId(orderId);
        return getOrderRequest;
    }

    public RejectOrderRequest rejectOrder(KlixConnector connector, String merchantId, String orderId, KlixRejectReason rejectReason) {
        RejectOrderRequest rejectOrderRequest = new RejectOrderRequest(connector);
        rejectOrderRequest.withMerchantId(merchantId);
        rejectOrderRequest.withOrderId(orderId);
        rejectOrderRequest.withReasonCode(rejectReason);
        return rejectOrderRequest;
    }

    public ApproveOrderRequest approveOrder(KlixConnector connector, String merchantId, String orderId) {
        ApproveOrderRequest approveOrderRequest = new ApproveOrderRequest(connector);
        approveOrderRequest.withMerchantId(merchantId);
        approveOrderRequest.withOrderId(orderId);
        return approveOrderRequest;
    }

    private ObjectMapper objectMapper() {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
        return objectMapper;
    }

}
