/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.klix;

import org.apache.http.client.HttpClient;
import org.apache.http.impl.client.HttpClients;

public final class KlixClient {

    private KlixEnvironment environment = KlixEnvironment.STAGING;

    private String apiKey;

    private HttpClient httpClient = defaultHttpClient();

    private HttpClient defaultHttpClient() {
        return HttpClients.createDefault();
    }

    public KlixEnvironment getEnvironment() {
        return environment;
    }

    public void setEnvironment(KlixEnvironment environment) {
        this.environment = environment;
    }

    public String getApiKey() {
        return apiKey;
    }

    public void setApiKey(String apiKey) {
        this.apiKey = apiKey;
    }

    public HttpClient getHttpClient() {
        return httpClient;
    }

    public void setHttpClient(HttpClient httpClient) {
        this.httpClient = httpClient;
    }

    public void validate() {
        // TODO check all parameters
    }

    public GetOrderRequest retrieveOrderDetails() {
        return new GetOrderRequest();
    }

}
