/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.klix;

import org.junit.jupiter.api.Test;

class LibraryTest {
    @Test
    void testSomeLibraryMethod() {
        KlixClient classUnderTest = new KlixClient();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
